name: Repository Dispatch

on: repository_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  merge_pr:
    name: Merge PR
    if: github.event.action == 'merge-pr'

    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Merge PR
      uses: justinyoo/github-pr-merge-action@v0.8.0
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        owner: ${{ github.event.client_payload.owner }}
        repository:  ${{ github.event.client_payload.repository }}
        issueId: '${{ github.event.client_payload.issueId }}'
        mergeMethod: Squash
        commitTitle: ''
        commitDescription: ''
        deleteBranch: 'true'
    - name: Send dispatch event for publish
      shell: bash
      run: |
        curl -X POST 'https://${{ secrets.AZURE_FUNCTIONS_NAME }}.azurewebsites.net/api/events/publish' -d '{ "owner": "devkimchi", "repository": "blog" }' -H "x-functions-key: ${{ secrets.AZURE_FUNCTIONS_KEY }}" -H "Content-Type: application/json"

  call_build_app:
    if: github.event.action == 'publish'
    uses: ./.github/workflows/build-app.yaml
    secrets: inherit

  call_deploy_gh_pages:
    if: github.event.action == 'publish'
    needs:
    - call_build_app
    uses: ./.github/workflows/deploy-gh-pages.yaml
    secrets: inherit
