name: Publish Static Web App to GH Pages

on:
  push:
    branches:
    - dev

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  call_build_app:
    uses: ./.github/workflows/build-app.yaml
    secrets: inherit

  call_deploy_gh_pages:
    needs:
    - call_build_app
    uses: ./.github/workflows/deploy-gh-pages.yaml
    secrets: inherit
